id: 2d86d3d1321a4aaab0a911cf71555232
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_437-The_Practice_Manual_of_Noble_Tara_Kurukulla-v1
  language: bo
  author: ''
  volume: {}
